const {PATHS}=require('../core/config');const {wiki}=require('../core/paths');const {slug}=require('../core/ids');
module.exports=async p=>{
 const app=p.app,api=app.plugins.plugins.quickadd?.api,cfg=JSON.parse(await app.vault.read(app.vault.getAbstractFileByPath(`${PATHS.config}/ontology-blueprints.json`))),types=JSON.parse(await app.vault.read(app.vault.getAbstractFileByPath(`${PATHS.config}/project-types.json`)));
 if(!api)throw new Error('QuickAdd API unavailable.');
 let preset={};try{preset=JSON.parse(p.variables?.preset||'{}')}catch{throw new Error('QuickAdd project preset is invalid JSON.')}
 const projectType=preset.projectType||await api.suggester(Object.entries(types).map(([key,x])=>`${key} — ${x.label}`),Object.keys(types));if(!projectType||!types[projectType])return'Project creation cancelled.';
 const ontology=cfg.modules.find(x=>x.id===preset.ontologyId)||null;if(preset.ontologyId&&!ontology)throw new Error(`Unknown ontology ${preset.ontologyId}`);
 const title=await api.inputPrompt('Project name','Use the approved project name; describe no unsourced requirements.');if(!title)return'Project creation cancelled.';
 const all=app.vault.getMarkdownFiles(),sameType=all.filter(f=>app.metadataCache.getFileCache(f)?.frontmatter?.type==='project'&&app.metadataCache.getFileCache(f)?.frontmatter?.project_type===projectType);const existingIds=sameType.map(f=>Number((app.metadataCache.getFileCache(f)?.frontmatter?.id||'').split('-').at(-1))).filter(Number.isFinite);const ordinal=Math.max(0,...existingIds)+1;const stableId=`${projectType}-M1-${String(ordinal).padStart(3,'0')}`;const folder=`${PATHS.projects}/${stableId} ${slug(title).toLowerCase()}`;if(app.vault.getAbstractFileByPath(folder))throw new Error(`Project folder already exists: ${folder}`);await app.vault.createFolder(folder);
 const day=new Date().toISOString().slice(0,10),projectPath=`${folder}/Project.md`,projectLink=wiki(projectPath),milestonePath=`${folder}/Milestone M1.md`,phasePath=`${folder}/Phase P1.1.md`,milestoneLink=wiki(milestonePath),phaseLink=wiki(phasePath);
 await app.vault.create(projectPath,`---\ntype: project\nid: ${stableId}\nproject_code: ""\nproject_type: ${projectType}\nstatus: backlog\npriority: normal\ntarget_start: null\ntarget_end: null\ncurrent_focus: ""\nblocker: ""\ncodelab_enabled: ${ontology?'true':'false'}\nontology: ${ontology?.id||''}\nprogress: 0\nhealth: unknown\nnext_action: ""\ncreated: ${day}\nupdated: ${day}\nschema_version: 1\ntags: [type/project]\n---\n# ${title}\n\n## Approved outcome\nRecord the owner-approved outcome and link its source. Do not infer requirements.\n\n## Acceptance\n- [ ] Each outcome has a measurable, source-backed completion condition.\n\n## Human controls\nStatus: \`INPUT[select(option(backlog), option(ready), option(in-progress), option(review), option(done), option(cancelled)):status]\` · Priority: \`INPUT[select(option(low), option(normal), option(high)):priority]\` · Target start: \`INPUT[date:target_start]\` · Target end: \`INPUT[date:target_end]\`\nFocus: \`INPUT[text:current_focus]\` · Blocker: \`INPUT[text:blocker]\` · Code Lab: \`INPUT[toggle:codelab_enabled]\`\n\n## Current state\n<!-- HEARTH:BEGIN PROJECT-STATE -->\nReconciled from linked TaskNotes, milestones, and phases.\n<!-- HEARTH:END PROJECT-STATE -->\n\n## Project pack\n- Charter: [[Project Charter]]\n- Roadmap: [[Roadmap]]\n- Index: [[Project Index]]\n- Board: [[Board]]\n- Milestone: [[Milestone M1]]\n- Phase: [[Phase P1.1]]\n`);
 await app.vault.create(milestonePath,`---\ntype: milestone\nid: ${stableId}-M1\nproject: "${projectLink}"\nnumber: M1\nstatus: backlog\nobjective: ""\nstart: null\nend: null\nrisk: unknown\nprogress: 0\ncreated: ${day}\nupdated: ${day}\ntags: [type/milestone]\n---\n# M1 — First milestone\n\n## Approved outcome\nDefine the milestone from the project’s linked approved requirements.\n\n## Human controls\nStatus: \`INPUT[select(option(backlog), option(ready), option(in-progress), option(review), option(done), option(cancelled)):status]\` · Objective: \`INPUT[text:objective]\` · Start: \`INPUT[date:start]\` · End: \`INPUT[date:end]\` · Risk: \`INPUT[select(option(unknown), option(low), option(medium), option(high)):risk]\`\n\n## Phases\n${phaseLink}\n\n## Acceptance\n- [ ] Linked phase outcomes have evidence and milestone review.\n`);
 await app.vault.create(phasePath,`---\ntype: phase\nid: ${stableId}-P1.1\nproject: "${projectLink}"\nmilestone: "${milestoneLink}"\nnumber: P1.1\nstatus: backlog\nsprint: ""\nrisk: unknown\nprogress: 0\ncreated: ${day}\nupdated: ${day}\ntags: [type/phase]\n---\n# P1.1 — First phase\n\n## Goal and exit criteria\nDerive a bounded phase from the linked milestone requirements.\n\n## Human controls\nStatus: \`INPUT[select(option(backlog), option(ready), option(in-progress), option(review), option(done), option(blocked), option(cancelled)):status]\` · Sprint: \`INPUT[text:sprint]\` · Risk: \`INPUT[select(option(unknown), option(low), option(medium), option(high)):risk]\` · Target: \`INPUT[date:target_end]\`\n\n## TaskNotes execution\n![[${PATHS.bases}/Active Project Tasks.base]]\n\n## Acceptance\n- [ ] Every task is a TaskNotes record and meets its linked criterion.\n`);
 const docs={
 'Project Charter.md':`# ${title} — Project Charter\n\n## Approved outcome\nLink the decision or requirement that authorizes this work.\n\n## Scope and constraints\nRecord only source-backed inclusions, exclusions, assumptions, constraints, and dependencies.\n\n## Acceptance\n- [ ] Criteria trace to approved sources.\n`,
 'Roadmap.md':`# ${title} — Roadmap\n\nProject milestone/phase projection. TaskNotes owns executable work.\n\n- ${milestoneLink}\n  - ${phaseLink}\n`,
 'Project Index.md':`# ${title} — Project Index\n\n- Project: ${projectLink}\n- Charter: [[Project Charter]]\n- Roadmap: [[Roadmap]]\n- Board: [[Board]]\n- Milestone: ${milestoneLink}\n- Phase: ${phaseLink}\n\n## Documents and evidence\n![[${PATHS.bases}/Active Project Documents.base]]\n![[${PATHS.bases}/Active Project Evidence.base]]\n`,
 'Board.md':`---\ntype: project-board\nid: BOARD-${stableId}\nproject: "${projectLink}"\ncreated: ${day}\nupdated: ${day}\ntags: [type/kanban]\n---\n# ${title} — Milestone Board\n\nMove only Milestone links between columns. Run **Hearth: Reconcile Project Board** after a move.\n\n## Backlog\n- ${milestoneLink}\n\n## Ready\n\n## In Progress\n\n## Review\n\n## Done\n\n## Cancelled\n\nTaskNotes remains execution truth.\n`};
 for(const [name,body]of Object.entries(docs)){const type=name==='Board.md'?'project-board':name==='Project Charter.md'?'project-charter':name==='Roadmap.md'?'roadmap':'project-index';await app.vault.create(`${folder}/${name}`,`---\ntype: ${type}\nproject: "${projectLink}"\ncreated: ${day}\nupdated: ${day}\ntags: [type/document]\n---\n${body}`)}
 if(ontology){const moduleFolder=`${PATHS.codelab}/Modules/${ontology.id} ${ontology.name.replace(/[^A-Za-z0-9]+/g,'-')}`;await app.vault.adapter.mkdir(moduleFolder);const modulePath=`${moduleFolder}/Module.md`;const source='3.RESOURCES/template/context/Ontologies.Canonical-Catalog.md';const moduleBody=`---\ntype: codelab\ncodelab_kind: module\nid: ${ontology.id}\nontology: "${ontology.name}"\napplication_path: "${ontology.path}"\nproject: "${projectLink}"\nmastery_state: not-started\nmastery: 0\nconfidence: 0\ncreated: ${day}\nupdated: ${day}\ntags: [type/codelab]\n---\n# ${ontology.id} — ${ontology.name}\n\n## Applied ontology source\n[[${source}]]\n\n## Real implementation surface\n${ontology.path}\n\n## DevCycle lessons\nCanonical lessons are linked from [[${moduleFolder}/Module]], and actual practice must use project TaskNotes with observed evidence.\n\n## Acceptance\n- [ ] Lesson drills point to existing execution tasks.\n- [ ] Mastery is recorded only from evidence.\n`;const old=app.vault.getAbstractFileByPath(modulePath);if(!old)await app.vault.create(modulePath,moduleBody);}
 const state=app.vault.getAbstractFileByPath(`${PATHS.state}/Project Context.md`);await app.fileManager.processFrontMatter(state,fm=>{fm.project=projectLink;fm.updated=day});await app.workspace.getLeaf(true).openFile(app.vault.getAbstractFileByPath(`${folder}/Board.md`));return`Created project ${stableId} in ${projectType}; ${ontology?`enabled Code Lab ontology ${ontology.id}`:'no ontology selected'}. A TaskNotes task is not fabricated.`;
};
