export const routes = {
  home: "/",
  pricing: "/pricing",
  features: "/features",
  contact: "/contact",
  signIn: "/sign-in",
  signUp: "/sign-up",
  onboarding: "/onboarding",
  dashboard: "/dashboard",
  settings: "/settings/profile",
  crm: "/crm/pipeline",
  projects: "/projects",
  support: "/support/inbox",
  marketing: "/marketing/campaigns",
  invoices: "/invoices",
  social: "/social/calendar",
  ai: "/ai",
  portal: "/portal",
  admin: "/admin/records",
} as const;
